# Copyright (c) Henry van Merode.
# Licensed under the MIT License.

# Build numbering format
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables:
  - name: releaseVersion
    value: 1.0.0

stages:
  - stage: hello_pipeline_stage
    displayName: Hello Pipeline
    jobs:
      - job: execute_snapshot_build_job
        displayName: Execute Snapshot Build Job
        condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))
        pool:
          vmImage: ubuntu-latest
        steps:
          # Perform a snapshot build in case the build starts from a feature branch
          - task: Maven@3
            displayName: 'Snapshot build'
            inputs:
              mavenPomFile: pom.xml
              mavenOptions: -Xmx3072m -Drevision=1.0.0-SNAPSHOT
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.17'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              goals: clean install

      - job: execute_release_build_job
        displayName: Execute Release Build Job
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
        pool:
          vmImage: ubuntu-latest
        steps:
          # Perform a release build in case the build starts from the master branch
          - task: Maven@3
            displayName: 'Release build'
            inputs:
              mavenPomFile: pom.xml
              mavenOptions: -Xmx3072m -Drevision=$(releaseVersion)
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.17'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              goals: clean install

            # Tag the pipeline if it is a release build (branch is master)
          - script: |
              echo "##vso[build.addbuildtag]$(releaseVersion)"
            displayName: 'Tag the pipeline with a release version'

            # Run it locally on the agent (branch is master)
          - script: |
              java -cp $(System.DefaultWorkingDirectory)/target/hello-pipeline-$(releaseVersion).jar Main $(releaseVersion)
            displayName: 'Execute app on the AzDo agent'
