# Copyright (c) Henry van Merode.
# Licensed under the MIT License.

# Build numbering format
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables:
  - name: revisionSnapshot
    value: "1.0.0-SNAPSHOT"
  - name: revisionRelease
    value: "1.0.0"
    #value: ""

stages:
  - stage: PipelineStage
    displayName: Build and Release pipeline
    jobs:
      - job: PipelineJob
        pool:
          vmImage: ubuntu-latest
        steps:
          # SNAPSHOT build
          - task: Maven@3
            condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))
            displayName: Snapshot build
            inputs:
              mavenPomFile: pom.xml
              mavenOptions: -Xmx3072m -Drevision=$(revisionSnapshot)
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.11'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              goals: clean install

            # Execute the artifact if it is a SNAPSHOT build
          - script: |
              java -cp $(System.DefaultWorkingDirectory)/target/hello-pipeline-$(revisionSnapshot).jar Main $(revisionSnapshot)
            condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Execute snapshot version on the AzDo agent'

            # RELEASE build
          - task: Maven@3
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
            displayName: Release build
            inputs:
              mavenPomFile: pom.xml
              mavenOptions: -Xmx3072m -Drevision=$(revisionRelease)
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.11'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              goals: clean install

            # Tag the pipeline if it is a RELEASE build
          - script: |
              echo "##vso[build.addbuildtag]$(revisionRelease)"
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Tag the pipeline with a release version'

            # Execute the artifact if it is a RELEASE build
          - script: |
              java -cp $(System.DefaultWorkingDirectory)/target/hello-pipeline-$(revisionRelease).jar Main $(revisionRelease)
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Execute release version on the AzDo agent'
