# Copyright (c) Henry van Merode.
# Licensed under the MIT License.

# Build numbering format
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables:
  - name: releaseVersion
    value: 1.0.0

stages:
  - stage: execute_build_and_deploy_stage
    displayName: Execute build
    jobs:
      - job: execute_build_and_deploy_job
        pool:
          vmImage: ubuntu-latest
        steps:
            # Perform a snapshot build in case the build starts from a feature branch
          - task: Maven@3
            condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Snapshot build'
            inputs:
              mavenPomFile: pom.xml
              mavenOptions: -Xmx3072m -Drevision=1.0.0-SNAPSHOT
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.11'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              goals: clean install

            # Perform a release build in case the build starts from the master branch
          - task: Maven@3
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Release build'
            inputs:
              mavenPomFile: pom.xml
              mavenOptions: -Xmx3072m -Drevision=$(releaseVersion)
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.11'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              goals: clean install

            # Tag the pipeline if it is a release build (branch is master)
          - script: |
              echo "##vso[build.addbuildtag]$(releaseVersion)"
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Tag the pipeline with a release version'

            # Run it locally on the agent (branch is master)
          - script: |
              java -cp $(System.DefaultWorkingDirectory)/target/hello-pipeline-$(releaseVersion).jar Main $(releaseVersion)
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Execute app on the AzDo agent'

            # Deploy it to target environment using curl (branch is master)
          - script: |
              curl --verbose --request POST --data @'$(System.DefaultWorkingDirectory)/target/hello-pipeline-$(releaseVersion).jar' https://example.com
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
            displayName: 'Deploy to target'
