# Copyright (c) Henry van Merode.
# Licensed under the MIT License.

# Build numbering format
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

stages:
  - stage: hello_pipeline_stage
    displayName: Hello Pipeline
    jobs:
      - job: execute_snapshot_build_job
        displayName: Execute Snapshot Build Job
        condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))
        pool:
          vmImage: ubuntu-latest
        steps:
          # Perform a snapshot build in case the build starts from a feature branch
          - task: Maven@3
            displayName: 'Snapshot build'
            inputs:
              mavenPomFile: pom.xml
              mavenOptions: -Xmx3072m -Drevision=1.0.0-SNAPSHOT
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.11'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              goals: clean install
